AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-stepfunctions-activity1

  Sample SAM Template for sam-stepfunctions-activity1

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64
  Api:
    OpenApiVersion: 3.0.3

Resources:
  NameActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      # アクティビティリソースは名前を自動生成してくれない
      Name: !Sub
        - "${AWS::StackName}-NameActivity-${v1}"
        - {v1: !Select [2, !Split [/, !Ref AWS::StackId ]]}


  FullNameStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/activity1.asl.yml
      DefinitionSubstitutions:
        NameActivityArn: !GetAtt NameActivity.Arn
      Policies:
        - Statement:
           - Effect: Allow
             Action:
               - logs:CreateLogDelivery
               - logs:GetLogDelivery
               - logs:UpdateLogDelivery
               - logs:DeleteLogDelivery
               - logs:ListLogDeliveries
               - logs:PutResourcePolicy
               - logs:DescribeResourcePolicies
               - logs:DescribeLogGroups
             Resource: "*"
        # Activityに対するpolicyとかを指定してないんだが、動くのはどういうわけ?
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt FullNameStateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ERROR

  FullNameStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub
        - "/aws/vendedlogs/states/${AWS::StackName}-FullNameStateMachine-${v1}-Log"
        - {v1: !Select [4, !Split ["-", !Select [2, !Split [/, !Ref AWS::StackId ]]]]}

Outputs:
  FullNameStateMachineArn:
    Description: "FullName state machine ARN"
    Value: !Ref FullNameStateMachine

  NameActivityArn:
    Description: "Name activity ARN"
    Value: !GetAtt NameActivity.Arn
